require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/**/*'
    - 'vendor/**/*'

Rails/EnumHash:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
RSpec/Rails/InferredSpecType:
  Enabled: false
RSpec/MultipleExpectations:
  Max: 5
Style/BlockComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/QuotedSymbols:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false